=== データ型と命名規則
==== 命名規則
* すべての名前は UTF-8 を使用してエンコードする必要があり、大文字と小文字が区別されます。
* （補足）属性名がストレージとスループットの使用量の測定に含まれるため、出来るだけ短くすることがベストプラクティス。

[cols=3,options="header", cols="40,20,40"]
|===
| コンポネント | 文字長 | その他制限
| テーブル名 
.2+| 3～255 文字 
.2+| 文字種制限（a-z、A-Z、0-9、_下線、-ダッシュ/ハイフン、.ドット）のみ
| インデックス名

| GSI/LSIのパーティションキー名
.3+| 1～255文字 
.3+| <<予約語>>、<<特殊文字>>の利用非推奨
| GSI/LSIのソートキー名
| LSIのユーザー指定の射影された属性名

| 属性名（上記以外） | 1文字以上、64KB未満 | <<予約語>>、<<特殊文字>>の利用非推奨
|===

==== データ型
* 共通して以下の制限があります
** 可変長なデータの場合
*** DynamoDB 項目の最大サイズ上限が 400 KBまで
*** シンプルなプライマリキーのパーティションキーの属性値として利用する場合の最大長： 2,048 バイト
*** 複合プライマリキーのソートキーの属性値として利用する場合の最大長：1,024 バイト

[cols=3,options="header", cols="20,20,60a"]
|===
| データ型の分類 | データ型 | 補足

.5+| スカラー型
| 数値 | * 正、負、または 0 （最大精度：38桁）
* エポックタイムを使用することで、日付またはタイムスタンプを数値データ型で表すことが可能

| 文字列 
| * UTF-8のUnicode + 
* 最小文字長0 + 
* https://en.wikipedia.org/wiki/ISO_8601[ISO 8601] の表記を使って日付またはタイムスタンプを文字列データ型で表すことが可能

| バイナリ | * 圧縮テキスト、暗号化データ、イメージなど、任意のバイナリデータが保存できる + 
* アプリケーションではbase64エンコードしてDynamoDBへの送信が必要、DynamoDBでは符号なしのバイト配列にデコードしてそのバイナリ属性の長さとして使用 + 
* バイナリ値の比較では、各バイナリデータを符号なしとして扱う + 
* 空のバイナリ可 + 

| ブール値 | ture または　false
| NULL | 不明または未定義の状態を表す

.2+|ドキュメント型
| リスト | * 順序付きの値のコレクション
* リスト要素に保存できるデータ型に制限はなく、リスト要素の要素が同じ型である必要はありません
* 例：`FavoriteThings: ["Cookies", "Coffee", 3.14159]`

| マップ | * 順序なしの名前と値のペアのコレクション + 
* マップの要素に保存できるデータ型に制限はなく、マップの要素が同じ型である必要はありません + 
* 例： + 
`{` + 
`    Day: "Monday",` + 
`    UnreadEmails: 42` + 
`    ItemsOnMyDesk: [` + 
`        "Coffee Cup",` + 
`        "Telephone",` + 
`        {` + 
`            Pens: { Quantity : 3},` + 
`            Pencils: { Quantity : 2},` + 
`            Erasers: { Quantity : 1}` + 
`        }` + 
`    ]` + 
`}` + 

| セット| セット | * 数値、文字列、またはバイナリ値のセットを表す型をサポート
* セット内の要素はすべて、同じ型である必要があります
* 各値は一意である必要があります
* 設定内の値の順序は保持されません
* 空のセットはサポートされていないが、空文字・空バイナリデータは許可
* 例：`["Black", "Green", "Red"]`

|===


==== 特殊文字
以下の文字はDynamoDBで特殊な意味を持つので、属性名での利用は非推奨

 (ハッシュ) # :: APIの実行時のAmazon DynamoDB式における実際の属性名の代わりとなるプレースホルダーの始まりを示す（属性名と予約語が同一の場合に利用できる） + 
[source, aws-cli]
----
aws dynamodb get-item \
     --table-name ProductCatalog \
     --key '{"Id":{"N":"123"}}' \
     --projection-expression "#c" \
     --expression-attribute-names '{"#c":"Comment"}'
----

(コロン):  ::  APIの実行時のAmazon DynamoDB式における実際の属性値の代わりとなるプレースホルダーの始まりを示す
[source, aws-cli]
----
aws dynamodb scan \
    --table-name ProductCatalog \
    --filter-expression "contains(Color, :c) and Price <= :p" \
    --expression-attribute-values file://values.json
----
`expression-attribute-values`のfile://values.jsonの中身
[source, json]
----
{
    ":c": { "S": "Black" },
    ":p": { "N": "500" }
}
----
上記は、以下と同じ意味
[source, aws-cli]
----
aws dynamodb scan \
    --table-name ProductCatalog \
    --filter-expression "contains(Color, :c) and Price <= :p" \
    --expression-attribute-values '{":c": { "S": "Black" }, ":p": { "N": "500" }}"'
----

(ドット). :: 
ドキュメント型のマップ要素の間接参照演算子 + 
* `MyMap.nestedField`


==== 予約語
* https://docs.aws.amazon.com/ja_jp/amazondynamodb/latest/developerguide/ReservedWords.html[DynamoDBの予約語]（調査時点：574文字）、属性名としての使用禁止、大文字と小文字が区別されない
