:stylesdir: .././css
:stylesheet: monospace.css

== 遊び編
NOTE: 書いてみたものの、たぶんある程度プレイしている人に重要なのは「 <<FF14の設定変更のおすすめ>>、<<FF14のおすすめ機能>> 」だけだと思う…

* 記載日時：2022/04/22
* 注意事項
** ネタバレは多大に含むので、嫌な人はご注意ください
** 色々バージョンアップされて覚えておらず、古い内容で記載してたらすみません
** 記載者はPlayStation5で遊んでいるので、PS5のコントローラーでの説明になります

=== はじめに
==== 拡張パッケージ
FF14はオンラインRPCゲームで約2-3年ごとに拡張パッケージを販売していて、拡張パッケージの略称でストーリーの状況などを呼ぶことがあるので一応ご紹介。 + 
（これ以外に最初にローンチされて吉Pさんが立て直す前の旧FF14（根性版/レガシー版）と呼ばれるものがあるが、これは現在プレイできない。）
[cols=5,options="header", cols="15,20,10,20,15"]
|===

| 略称 
| 正式名称(パッチ)/英語名 
| MAXLv 
// | 主要都市 
| 追加ジョブ（職） 
| 追加種族

| 新生 
| 新生エオルゼア（2.0） + 
 / EORZEA
| Lv50 
// | （俗にいう三国） +
// リムサ・ロミンサ +
// ウルダハ +
// グリダニア
| 他で追加されないすべて + 
（双剣士は他職Lv15から）
| デフォルト5種族

| 蒼天 + 
（そうてん） 
| 蒼天のイシュガルド（3.0） +
 / HEVENSWARD
| Lv60 
// | イシュガルド + 
// イディルシャイア
| 暗黒騎士 +
占星術師 +
機工師
| アウラ♂♀

| 紅蓮 + 
（ぐれん）
| 紅蓮のリベレータ（4.0） +
 / STORMBLOOD
| Lv70 
// | ラールガーズリーチ +
// クガネ +
// （ドマ町人地）
| 侍 + 
赤魔導士
| －

| 漆黒 + 
（しっこく）
| 漆黒のヴィランズ（5.0） + 
 / SHADOWBRINGERS
| Lv80 
// | クリスタリウム +
// ユールモア
| ガンブレイカー +
踊り子
| ヴィエラ♀ +
 ロスガル♂

| 暁月 +
（ぎょうげつ）
| 暁月のフィナーレ（6.0） + 
/ ENDWALKER
| Lv90 
// | オールドシャーレアン +
// ラザハン
| 賢者 +
リーパー +
| ヴィエラ♂

|===

==== データセンター（DC）とワールドと移動
FF14はオンラインゲームなので遊ぶサーバーを決める必要があり、DC（エリア / 論理データセンタ）とワールド（サーバ）を選ぶ。 + 
既に友人が遊んでいるなら友人と同じDC/ワールドを選べばよいが、混雑DCやワールドだとキャラクター作成制限がある、特にここがいいが無ければ、とりあえず近場のデータセンターの気になる名前のワールドを選べは良い（ キャラ作成が可能かどうかは https://jp.finalfantasyxiv.com/lodestone/worldstatus/[ワールド状況^] から）。 + 
キャラを作った後でも、「ワールド間移動」や「論理データセンタ間移動」ができ、追加課金で「 https://jp.finalfantasyxiv.com/lodestone/playguide/option_service/world_transfer_service/[ホームワールド変更サービス^] 」も利用できるので気楽に選んでも大丈夫といえば大丈夫。

* エリア
** 日本、北米、ヨーロッパ、オセアニア
* 論理データセンタ（日本）：

[cols=2,options="header",cols="25,75"]
|===
| 論理データセンタ | 特徴（噂程度のまとめ）

| Elemental | 昔からあるDCの１つ、Tonberryに英語圏の方が集まっていて稀に異文化交流があった、日本と北米で攻略方法が異なり稀に混乱が発生していたらしい
| Gaia  | 昔からあるデータセンタの１つ、レガシー先輩が多いと噂、0時に人が居なくなる平和なところ
| Mana | 戦闘系エンドコンテンツに挑む人御用達のところ
| Meteor | 暁月の前くらいに創設、ワールド再編された過疎DC、新規さん大歓迎だが、パーティ募集がほぼない
|===

* DC間の作成キャラクター移動について

キャラクターごとにレベルなどが決まっている、複数のキャラを作成することも可能だが、育てたキャラで他のDCでも遊びたいことがあるのでその方法のご紹介。 + 
実行方法や制限事項の詳細は「 https://jp.finalfantasyxiv.com/lodestone/playguide/contentsguide/worldvisit/[トラベルガイド^] 」参照。

[cols=4,options="header",cols="15,15,15,55"]
|===
| 対象 | 正式名称 | 可否 | 補足 

| ワールド間移動 | ワールド間テレポ | キャラ移動可能 | 三国のエーテライトから移動可能（一部制限あり）
| 論理データセンタ間移動 | データセンタートラベル | キャラ移動可能 | ログインのキャラ名から「他のデータセンターに遊びに行く」から移動可能（一部制限あり）

| エリア間移動
3.+| 移動できない（新規キャラ作成は可能）
|===

==== クラスとジョブとロール
FF14ではジョブ（職）に着替えることで、そのジョブに応じたアクションが実行できるようになり、ダンジョン攻略などでのパーティプレイではそのジョブに応じた役割（ロール）をこなしていく感じになる。 + 
ストーリーはどれか1つの戦闘職（バトルクラス）のジョブのレベリングにより進めることが出来る。 + 
戦闘職（バトルクラス）には、ジョブになるための前提クラスがあるものがあり、対象クラスのレベルを上げて特定クエストをこなして、ジョブになれるソウルクリスタルを貰い、ソウルクリスタルを装備することで対象ジョブになれる。 + 
好みの職に着替えながら好きに遊んでください。好みの職がストーリー進めないと出ない場合は他の似てるロールのをこなしていくとよいです。

===== 戦闘職のロール
[horizontal]
タンク:: 敵からの攻撃を受ける人 + 
一番最初に敵を殴って敵視（ヘイト）を稼いで殴られ続ける＋他の人が動きやすいように敵を誘導する（後ろを向ける）、ダンジョンでは先導役もこなす + 
殴る以外の役割が多いことから若干不人気(？)だが、ものすごくシャキりやすいので時間の無い人にはおすすめ
ヒーラー:: パーティメンバー（主にタンク）を回復する人（ずっと70%以上のHP維持くらいを目指すとタンクさんも安心） + 
また、回復が不要な時は敵を攻撃するのもお仕事、魔法職なので基本的には詠唱が必要 + 
比較的シャキりやすい
DPS:: ひたすら敵を殴る人（火力を出す係） + 
ダンジョンでは、タンクさんより先に敵を殴ったり、タンクさんと違う敵を殴ると敵が強くて殺されかねないので、殴る敵には注意（アシストマクロ推奨） + 
3匹以上だったら範囲技でOK、対象ジョブが多いのでシャキりにくい
** 近接物理DPS：敵に近づいて殴る人 + 
… 方向指定があるため技により殴る位置を変えると火力が出せる、ダンジョンなどでのリミットブレイクをボスに対して打つのも大体このロール
** 遠隔物理DPS：敵から離れて殴れる人 + 
…近接より少し火力が劣るが支援系の技もある、移動の自由度が高いので比較的にギミックを任される人
** 遠隔魔法DPS：魔法使う人 +
 … 魔法職なので基本的には詠唱が必要、ヒラ以外の蘇生持ち（黒以外）、リミットブレイクが範囲焼きなのでダンジョンでのまとめで打つ場合もある

* 参考： https://www.finalfantasyxiv.com/beginner/column/page01.html[初心者向けの公式説明はこちら^]  + 
（会話形式の説明が好きな人は上記からどうぞ）

===== 戦闘職ジョブ・クラス一覧
** 戦闘職（バトルクラス）のジョブの詳細は https://jp.finalfantasyxiv.com/jobguide/battle/[ジョブガイド^] 参照（上部の「初期クラス：XXX」でクラスを開始し「ジョブ開始クエスト」の達成で開放）

[col=7, options="header",cols="10,10,20,10,10,10,10"]
|===
| 種類（補足） | ロール | ロール補足 + 
（マクロの役割） | ジョブ | 前提クラス | 開始Lv | 他のカテゴリ

.20+| バトルクラス + 
（戦闘職）
.4+| タンク
.2+| メインタンク（MT）系
| 暗黒騎士
| －
| lv30
.12+| ファイター

| 戦士
| 斧術士
| lv1

.2+| サブタンク（ST）系
| ガンブレイカー
| －
| lv60

| ナイト
| 剣術士
| lv1 

.12+| DPS 
.5+| 近接物理DPS + 
（D1,D2）
| モンク
| 格闘士
| lv1

| 竜騎士
| 槍術士
| lv1

| 侍
| －
| lv50

| リーパー
| －
| lv70

| 忍者
| 双剣士
| lv1

.3+| 遠隔物理DPS + 
（レンジ：D3）
| 吟遊詩人
| 弓術士
| lv1

| 機工士
| －
| lv30

| 踊り子
| －
| lv70

.3+| 遠隔魔法DPS + 
（キャス：D4）
| 黒魔導士
| 呪術士
| lv1
.8+| ソーサラー

| 召喚士
| 巴術士
| lv1

| 赤魔導士
| －
| lv50

| 特定コンテンツ専用
| 青魔導士
| －
| lv1

.4+| ヒーラー
.2+| ピュアヒラ（PH：H1）系
| 白魔導士
| 幻術士
| lv1

| 占星術士
| －
| lv30

.2+| バリアヒラ（BH：H2）系
| 学者
| 巴術士
| lv1

| 賢者
| －
| lv70

|===

===== 戦闘職の注意事項
* ジョブになるには「ソウルクリスタルの装備」が必要です、外れてるとただのクラスなので注意しましょう
** ジョブの装備などを一式まとめて管理する「 https://jp.finalfantasyxiv.com/uiguide/equipment/equipment-gearset/equipment_set.html[ギアセット^] 」にソウルクリスタルを装備したあとの衣装をセットしておけば安全です
* 対象のクラス/ジョブのアクションだけでなく「ロールアクション」も利用可能なので両方使いましょう
* 対象のクラス/ジョブのアクションが利用できるようになるには「 https://jp.finalfantasyxiv.com/lodestone/playguide/db/quest/?category2=6[クラスクエ^] 」と呼ばれるクエストをこなす必要があります（漆黒、暁月はLvMaxのみ）

===== クラフターとギャザラー一覧
ストーリーを進める上では特に育てる必要はない（コレクター要素的なものが大きい、上手くやるとギルが稼げる）。 + 
なお、クラフターが作り、ギャザラーが取ってくる素材は、ギルを出せばマーケットでだいたい買える。 + 
クラフターは自分の名の入ったアイテムを作成できる、クラフターは釣り手帳を埋めるなどのコレクター要素を満たせる。 + 
貴重アイテムや貴重素材をマーケットで別プレイヤーに上手く売ることでギルが稼げる。

** 生産職（クラフター）・収集職（ギャザラー）のジョブの詳細は https://jp.finalfantasyxiv.com/crafting_gathering_guide/[クラフター・ギャザラーガイド^] 参照（上部の「クラス開放クエスト」の達成で開放）
** 以下は、 https://game8.jp/ff14/314054[【FF14】クラフタージョブの情報まとめ丨作れる物【初心者向け解説有り】^] の抜粋

[col=4, options="header", cols="20,20,20,40"]
|===
| 種類（補足） | ジョブ | 開放都市 | 主な役割

.8+| クラフター + 
（生産職）
| 木工師
| グリダニア
| ・竜騎士/吟遊詩人/黒魔道士/白魔道士の武器 + 
・ギャザラーのアクセサリー + 
・ハウジング関連（製作レシピ数最多） + 
・マウント(飛ぶベッド)

| 鍛冶師
| リムサ・ロミンサ
| ・タンク4種/モンク/侍/忍者/機工師/踊り子の武器 + 
・9割方のギャザクラの主、副道具を製作可
・ハウジング関連

| 甲冑師
| リムサ・ロミンサ
| ・タンクと竜騎士の鎧
・錬金術師と調理師の主道具
・ハウジング関連
・チョコボ装甲

| 彫金師
| ウルダハ
| ・アクセサリー製作に特化
・裁縫師の主道具
・赤魔道士と占星術師の武器が製作可能
・ハウジング関連（木工師に次ぐレシピ数）

| 革細工師
| グリダニア
| ・足防具が多め
・木工と同じで作れる種類が豊富
・おしゃれ装備も足多め
・ハウジング関連（少なめ）

| 裁縫師
| ウルダハ
| ・キャスターやヒーラーと相性良し
・防具製作の要。製作可能部位が豊富
・上半身おしゃれ装備の大半を担う
・ハウジング関連

| 錬金術師
| ウルダハ
| ・色々なジョブで使用する中間素材を製作
・回復薬やステータス上昇の薬品を製作
・召喚士と学者の武器
・ハウジング関連

| 調理師
| リムサ・ロミンサ
| ・色々なジョブで使用する中間素材を製作
・回復薬やステータス上昇の薬品を製作
・召喚士と学者の武器
・ハウジング関連

.3+| ギャザラー
| 園芸師
| グリダニア
| 木材の伐採に加え、果実や薬草、繊維作物の収穫など

| 採掘師
| ウルダハ
| 鉱石や原石の採掘、石材の切り出しなど

| 漁師
| リムサ・ロミンサ
| 魚に始まり、貝類や甲殻類など（主釣りコレクター要素あり）

|===

=== 始め方

NOTE: アカウント登録して、好きなハードにアプリをインストールして、アカウントと紐づけて遊ぶだけ +
ただ、60GB以上あるのでハード要件確認の上、1日はかかると思ったほうがいい

==== ハード要件
PlayStation4/5、WindowsPC、MacPC（他に比べると今一との噂あり）があり、自分の好きなハードにインストールして遊べます、下記参照。
* https://jp.finalfantasyxiv.com/system_requirements/[動作環境（ハードにより異なる）^]

==== 推奨付属品
[horizontal]
キーボード:: PS4/5でもチャットするのに必要、一応、画面上の補助キーボードはあるし、定型文もあるけど超不便
ゲーム用コントローラー:: PCで遊ぶのに移動がキーボードorマウスは結構つらいのでPCでもあるとよいらしい
マウス:: （あると便利かも程度）混戦した場合にターゲットをポイントしたりするのに便利らしい

==== フリープレイと通常プレイ
フリープレイで無料でだいぶ遊べるので、最初はフリープレイがおすすめ（一部制限）。 + 
続編をやりたくなったら通常プレイ（パッケージ購入＋月額課金）したらOKかと。

[cols=5,options="header"]
|===
| 種類
| 特徴
| 料金
| 公式URL
| 補足

| フリープレイ
| 日本語版：～蒼天まで + 
英語版：～紅蓮まで
| 無料
| https://www.finalfantasyxiv.com/freetrial/[フリートライアル^]
| PS4/5の始め方も上記から

| パッケージ購入＋月額課金
| 購入したパッケージ分まで遊べる
| コンプリートパック（30日間無料）：約6500円 + 
月額課金： 約1500円 +
（他プランもあり）
| https://jp.finalfantasyxiv.com/product/?utm_source=pr2&utm_medium=top_btmbtn&utm_campaign=jp_buynow[FF14公式の商品情報^]
| 拡張ごとに買えるけどコンプリートパックが安い

|===

* https://game8.jp/ff14/345590[参考：フリープレイの制限事項^]：
** マーケットボード、トレード、モグレター、リテイナーの利用ができない
** ゲーム内チャット機能のリンクシェル（LS）、クロスワールドリンクシェル（CWLS）の作成はできない（加入は可能）
** パーティ募集機能が利用できない（自動マッチングのコンテンツファインダーは利用可能、誘われるパーティに参加は可能）
** PVPコンテンツの「ザ・フィースト」はプレイできない
** 特定のチャット機能（shout、yell、tell）
** 1ワールド1キャラクターまで、所持ギル：300,000ギルまで
** プレイヤーズサイト「Lodestone」や「公式フォーラム」へのログインはできない
** 冒険サポートアプリの「ファイナルファンタジー XIV コンパニオ」も利用できない

==== アカウント登録 + インストール
https://www.finalfantasyxiv.com/freetrial/[フリートライアル^] 参照。

==== インストール後の流れ
「 https://jp.finalfantasyxiv.com/game_manual/start/[FF14ゲームマニュアル：ゲームをはじめる^] 」参照。

* 主な手順と補足（上記のリンク先に書いてあるのでその手順参考）
** アプリ起動
** アカウントの紐づけ
** ゲームスタート（ログイン）
*** DC選択（参考： <<データセンター（DC）とワールドと移動>> ）
*** キャラクター作成（ https://game8.jp/ff14/294817[種族、性別^]、容姿、誕生日と守護神、クラス選択（最初の戦闘職）を選択）
**** クラス（職/ジョブ）はゲーム内でいくらでも変更できるので気楽にどうぞ（参考：<<クラスとジョブとロール>>）
***** 種族によって初期ステータスが少しだけ違うので適する職というものはあるが、基本誤差なので好きな見た目でOK（フリープレイはアウラまで）
**** 容姿の髪の色/髪型もゲーム内で変更可能
**** 上記以外の種族・性別・容姿は課金アイテムの幻想薬（約1000円）で変更可能（ https://game8.jp/ff14/294861[幻想薬の使い方^] ）
**** キャラクター名称も課金で変更可能（ https://jp.finalfantasyxiv.com/lodestone/playguide/option_service/character_renaming_service/[キャラクター名変更サービス^] ）
**** 誕生日と守護神の変更方法は知らない。ただ意識したことは無いのでプロフィール的な意味だけだと思われる
** ワールド選択
** ゲームスタート！

==== 主な進め方
* 基本的にはメインクエスト（炎外観のクエスト）を追って進めればOK（ https://jp.finalfantasyxiv.com/uiguide/know/faq-display/interface_npc_icon.html[クエストアイコンの違い^]）
* あと、クラスクエストを進めないと対象のクラスやジョブでのアクション（技）が増えないので、定期的にギルドや開放場所を見に行って、そちらのクエストも忘れずに進める（～50まで：Lv5刻み、～70まで：Lv2刻み、Lv80、Lv90）
** ＋マークが付きの機能開放クエストは、新しいクラス・ジョブ開放や蛮族クエ、風脈開放クエなどがあるので進めるのはあり
** レベリング補足：
*** メインクエストを進めるだけで戦闘職１職分がカンストする必要経験値がたまるらしい基本不要 + 
（念のため、HPバーの右に月マークが表示される https://game8.jp/ff14/296477[レストエリア^] でログアウトだけはしておこう）
*** ので、興味なければ他のサブクエストは無視しても大丈夫、ご参考までに<<クエストの種類とおすすめ度>>

=== FF14の設定変更のおすすめ
FF14のUI系の設定は相当いじれるのでご紹介。 + 
困っていなければすぐに修正する必要はないので、内容だけ見ておいて、困ってからそういえば変えられたなと記憶に残ったのを適用してみるくらいで大丈夫です。 + 
下記に紹介する以外にもキャラクターコンフィグを中心におすすめ設定を沢山の方が出しているので、ご参考に。

* 参考： https://sarachantubuyaki.jp/finalfantasyxiv/character-config/[【FF14】設定しておくべきキャラクターコンフィグ^]

* 凡例：★★★：知っておきたい、★★☆：必要になったらどうぞ

[col=5, options="header", cols="15,10,25,25,25"]
|===
| 内容 | おすすめ度 | 場所 | よくある課題 | 補足 

| キーバインドの変更 
| ★★★
| メインコマンド + 
＞システムメニュー + 
＞システムコンフィグ  + 
＞コントローラーアイコン + 
＞「ボタンカスタマイズ」ボタンより +
 + 
（PC）システムメニュー + 
＞キーバインド変更
| ・決定キーを○から×に変えたい + 
・右スティック押し込みで主観に切り替わるのを止めたい + 
…などに便利
| －

| HUDの変更 + 
（画面要素の移動、大きさ変更）
| ★★★
| メインコマンド + 
＞システムメニュー +  
＞HUDレイアウトの変更 + 
 + 
設定詳細は https://game8.jp/ff14/462547#hl_2[HUD設定方法^] 参照
| ・コンテンツウィンドウの要素が大きいので小さくしたい + 
・ウィンドウの位置を移動させたい + 
・アライアンスパーティーメンバー欄がでかすぎる + 
…などに対処できて便利
| コントローラーの場合 https://jp.finalfantasyxiv.com/uiguide/faq/faq-interface/interface_pad_mouse.html[マウスモード（L1ボタン+右スティック押込み）^] で操作すると移動させやすい

| （PC）ダイレクトチャットモードのOFF
| ★★★
| メインメニュー + 
＞システムメニュー + 
＞キャラクターコンフィグ + 
＞操作設定 +
＞ダイレクトチャットモードを有効にする + 
 + 
詳細 https://jp.finalfantasyxiv.com/uiguide/communication/communication-chat/chat_directmode.html[ダイレクトチャットモードってなに？^] 参照

| キーボードのショートカットキーで技を出したい場合に必須
| 移動はコントローラー、技はキーボードのショートカットキーで操作する場合に良いらしい

| 召喚獣の大きさ変更
| ★★★
| チャット欄にコマンド実行 + 
`/petsize all small` + 
 + 
詳細は https://game8.jp/ff14/285890[【FF14】召喚獣のサイズ変更方法とサイズ比較【召喚士】^]参照
| 召喚士の使うペット（召喚獣）がでかすぎて周囲が見えなくなる時の対処法
| FFの召喚獣なら大きいほうがいいって人は変更しなくてOK

| ナビマップの北固定 + 
（or 北固定をやめる）
| ★★★
| ナビマップの歯車クリック + 
（キャラが向いている方向を上にしたい場合は歯車の固定を外す）
| ナビマップがくるくる回って北がわからなくなる場合に便利
| コントローラーの場合 https://jp.finalfantasyxiv.com/uiguide/faq/faq-interface/interface_pad_mouse.html[link マウスモード（L1ボタン+右スティック押込み）^] で操作するとクリックしやすい

| 一度見たムービーを自動スキップ
| ★★★
| メインメニュー + 
＞システムメニュー + 
＞キャラクターコンフィグ + 
＞操作設定 +
＞全般タブ +
＞カットシーンスキップ設定 + 
＞一度見たコンテンツ内のカットシーンをスキップする +
 + 
詳細 https://connietarte.com/useful/movie-skip/[【FF14】一度見たムービーを自動でスキップする方法^] 参照

| 一度見たムービーの都度スキップが面倒な場合に便利 + 
 + 
（また、IDなどで初見と間違われないように大半の人が設定している）
| うっかりスキップして見れなくなったムービーは宿屋などの「愛用の紀行録」から見れる（参考 https://choice-antenna.com/ff14-howtomoviereplay/[【FF14】見逃した＆もう一度見たいムービーはどこで見れるの？スキップしても慌てない！^]） + 
ただし、全部じゃないので注意、かつ、初見時はムービーを楽しむのが良い

| バトルエフェクトを非表示/簡易表示にする
| ★★★
| メインメニュー + 
＞システムメニュー + 
＞キャラクターコンフィグ + 
＞操作設定 +
＞キャラクタータブ +
＞カットシーンスキップ設定 + 
＞バトルエフェクト設定 +
 + 
詳細 https://connietarte.com/useful/battle-effect-off/[【FF14】他プレイヤーのバトルエフェクトを非表示にする方法^] 参照

| ・人が多い時にエフェクトが派手すぎて敵がどこに居るのかわからない + 
・人が多い時にエフェクトが原因かは不明だが動作が重い + 
…の場合の解決法として試す
| 他人のエフェクトは非表示もしくは簡易表示にはしておいたほうがいい + 
PTや自分を簡易表示にするかはお好みでどうぞ

| ホットバーの全ジョブ共通化
| ★★☆
| メインコマンド + 
＞システムメニュー + 
＞キャラクターコンフィグ + 
＞ホットバー設定 + 
＞共有タブ +
 + 
詳細は https://jp.finalfantasyxiv.com/uiguide/know/know-hb/hotbar_shared.html[公式] や https://connietarte.com/useful/doh-hotbar-share/#op2[【FF14】クラフターのホットバーを共通（同じ）にする方法^] 参考
| ・全ジョブで同じアクション（テレポ・スプリントなど）を利用したい + 
・生産職で共通のスキルを一つのホットバーにまとめたい + 
…の場合に便利
| －

| ダブルクロスホットバーの有効化
| ★★☆
| メインコマンド + 
＞システムメニュー + 
＞キャラクターコンフィグ + 
＞ホットバー設定 + 
＞XHB基本タブ + 
 +  
詳細は https://connietarte.com/useful/wxhb/[【FF14】慣れると便利！ダブルクロスホットバーの設定方法^] 参照
| コントローラーでの戦闘で16個じゃ足りない、かつ、ホットバーの切り替えは上手く出来ない場合に便利
| －

https://ff14beginner.com/beginner/system/chat-customize/

.2+| チャットの色や音をLSによって変更する
.2+| ★★★
| 【色】メインメニュー + 
＞システムメニュー + 
＞キャラクターコンフィグ + 
＞チャットログ +
＞全般タブ +
＞ログカラー設定 + 
 + 
詳細 https://jp.finalfantasyxiv.com/uiguide/communication/communication-chat/chat_display_color.html[【ログカラーの変更^] 参照

| どのLSでの発言かすぐに分からない場合の解決法として便利
| LSの誤爆の判断にも便利

| メインメニュー + 
＞システムメニュー + 
＞キャラクターコンフィグ + 
＞チャットログ +
＞全般タブ +
＞着信タブ + 
 + 
詳細 https://connietarte.com/useful/chat-sound/[【FF14】チャットやエモートの受信音を鳴らす方法^] 参照
| チャットに気づかない場合の解決法として便利
| －

| チャット欄の追加・大きさ・数変更
| ★★★
| 詳細は https://ff14beginner.com/beginner/system/chat-customize/[チャットを使いやすく設定しよう！^] 参照
| チャット欄が小さい、チャット分けたいなどの便利に便利
| チャット欄は、なぜかHUDでは操作できない…



| 敵のHPのパーセント表示
| ★★☆
| メインコマンド + 
＞システムメニュー + 
＞キャラクターコンフィグ + 
＞ユーザインタフェース + 
＞HUDタブ + 
＞選択対象のHP比率を表示する
 + 
詳細は https://connietarte.com/useful/hp-percent/#index_id3[【FF14】敵モンスターの残りHPをパーセント表示する方法^]参照
| ・零式などの火力チェックの目標%への達成度合いなどを見るときに便利
| 零式民は必須 + 
捕まえる系のギルドリーブでも30%以下を目安にできるのであるとよい

| 時計表示を増やす + 
（ET：エオルゼア時間、 + 
　LT：ローカル時間、 +
　ST：サーバ時間）
| ★★☆
| メインコマンド + 
＞システムメニュー + 
＞キャラクターコンフィグ + 
＞ユーザインタフェース + 
＞HUDタブ + 
＞時計の表示タイプで表示対象を選ぶ
 + 
詳細は https://arisagame.blog.jp/archives/13302298.html[FF14 ＥＴエオルゼア時間とＬＴローカル時間を２つ並べて表示^]参照
| 日常生活においてローカル時間を表示したいし、 ギャザラーのアイテム収集時間を知るためにエオルゼア時間も知りたい場合に便利
| モブハントにおいてもETが使われるので、ETも表示しておく方がいい

|===

=== FF14のおすすめ機能
FF14にはメインクエスト上は説明されない機能が稀にあるので、おすすめ機能をご紹介。 + 
こちらも軽く一読して利用したくなったら利用したらいいくらいのです。 + 

* 凡例：★★★：外せない／知っておきたい、★★☆：おすすめだけど後からでもいい

|===
| 内容 | おすすめ度 | 場所 | よくある課題・メリット | 補足 

| チョコボカバン + 
（所持品拡張）
| ★★★
| マイキャラクター + 
＞ チョコボかばん 
| 所持品の枠が足りない場合の避難先置き場、その１
| －

| 愛憎品キャビネット + 
（所持品拡張：季節系イベントで貰える装備を格納できる）
| ★★★
| 宿屋などの「愛憎品キャビネット」に格納する + 
（耐久度が100％以外は入れられないので修理してから実施）
| 所持品の枠が足りない場合の避難先置き場、その２
| ミラプリのミラージュプレートのアイテムとしても利用可能

| ギアセット + 
（特定ジョブ装備への一括お着換え機能）
| ★★★
| マイキャラクターの上部「ギアセットリスト」より + 
 + 
（詳細： https://jp.finalfantasyxiv.com/uiguide/equipment/equipment-gearset/equipment_set.html[ギアセット] 参照）
| ジョブを変えるたびにキャラが丸裸になって恥ずかしいことを防ぐ
| ギアセットの名前が前提クラス名だった場合に、ソウルクリスタルの装備を忘れているので、装備して再設定すべし

| さいきょう + 
（最強装備自動選択機能）
| ★★★
| マイキャラクターの上部「さいきょう」より + 
 + 
（詳細： https://jp.finalfantasyxiv.com/uiguide/equipment/equipment-saikyo/equipment_best.html[さいきょう装備] 参照）
| 強い装備が手に入った時に対象部位を選ばずとも「さいきょう」一発で装備変更できる
| －

.2+| ミラプリ機能 + 
（装備の見た目変更）
.2+| ★★★
| 【個別変更】 + 
対象装備を選択 + 
＞武具投影 + 
＞変更したい装備を選ぶ + 
.2+| 強いけど装備がダサい時に他の見た目に変更したい時に便利 + 
 + 
詳細や前提条件は https://game8.jp/ff14/301040[【FF14】ミラプリ解放条件｜やり方^] 参照
.2+| ミラプリではないが特定装備は色変更が可能（装備選択＞染色する） + 
 + 
詳細や前提条件は https://game8.jp/ff14/301044[【FF14】染色の解放方法｜やり方^] 参照

| 【一括変更】 + 
宿屋などの「ミラージュドレッサー」で実施 + 
1. 装備をドレッサーに登録 + 
2. ミラージュプレートにミラプリしたい装備を設定 + 
3. ギアセットにミラージュプレートを関連付ける

| チャットのチャネルの切り替え
| ★★★
| 【３つの方法あり】 + 
・左の吹き出しアイコンからチャネルを選択 + 
・チャット欄にコマンド入力（ `/p、/cwls1` など） + 
・キーボードショートカットに追加（Alt + P など） + 
 + 
詳細は https://jp.finalfantasyxiv.com/lodestone/character/2185992/blog/2926529[チャットを切り替えよう！^] 参照
| 特定のリンクシェル（/ls）/クロスワールドリンクシェル（/cwls）で話すために切り替えたい場合に利用
| コマンドの場合、チャット欄は切り替えずに発言チャネルを変更できる + 
（ `/p よろしくお願いしますー！` など）

| オートラン機能
| ★★☆
| 左スティックで移動 ＋ L1 + 
（解除したいときは左スティックを引く）
| （飛ぶマウント持ちなどで）エリアの端に移動しないといけないがスティック操作をずっとしているのが疲れる場合に便利
| －

| フォーカスターゲット（FT） + 
（対象の状態を常に表示する機能）
| ★★☆
| 対象を選択して□ボタン + 
＞フォーカスターゲット + 
| ・DPS：ボスのdot系技の更新タイミングを見たい + 
・ヒラ：タンク回復中でも敵の詠唱バーを見たい + 
…の場合に便利
| ターゲット含む詳細は https://game8.jp/ff14/292302[【FF14】ターゲット情報とフォーカスターゲット情報の仕様^] 参照

| マクロを組む + 
（一定の行動を1ボタンで実行出来るようにする）
| ★★☆
| メインコマンド + 
＞システムメニュー + 
＞マクロ管理 + 
 + 
詳細は https://game8.jp/ff14/292803[【FF14】マクロとは？マクロの作り方とコマンドの説明^]参照 + 
（マクロエラーの非表示は冒頭に `/macroerror off` を設定）
| ・タンクと同じ敵をターゲットしたい（アシストマクロ） + 
・挑発 / 蘇生をしたことをメンバー人知らせたい（挑発マクロ、蘇生マクロ） + 
・タンクをターゲットした状態でタンクがターゲットしている敵を殴りたい（ttマクロ）
…の場合に便利
| アシスト・挑発・蘇生マクロは零式挑戦時も含めてあるとよい + 
ただし、マクロは先行入力ができないので火力を極めたかったらttマクロ系は使わないほうがいい + 
変身マクロとかも面白いのでFCイベントの一興などにはおすすめ

|===

=== FF14の冒険の補足
==== クエストの種類とおすすめ度
クエストという表現であっているか分からないが、クエストやコンテンツを俗称も含めて分けておすすめ度をつけたもの。 +
ストーリーを進める上で必要かどうかの参考にどうぞ（あくまで独断なので異論は大いに認めます）。

* 凡例：★★★：外せない、★★☆：おすすめだけど後からでもいい、★☆☆：好きな人には嵌る、☆☆☆：お好きにどうぞ

[col=3, options="header", cols="20,10,70"]
|===
| クエスト／カテゴリ | おすすめ | 補足 

| メインクエスト | ★★★ | これを進めるゲームなので必須
| クラスクエスト | ★★★ | 対象ジョブのアクションを増やすために必須
| 蛮族クエスト | ★☆☆ | ストーリー好き、マウントが欲しいなどなければ特に…
| ギルドリーブ | ☆☆☆ | レベリングが必要じゃなければ特に…
| ギルドオーダー | ☆☆☆ | レベリングが必要じゃなければ特に…
| バハムートクエスト | ★★☆ | ストーリーが良い、戦闘系の高難易度コンテンツ、Lv50で挑むのは零式と同じ扱い（戦闘が苦手な人は制限解除でレッツトライ）
| 蛮神系クエスト | ★★☆ | ストーリーが良い、装備集めもできる、ただ、戦闘が苦手なひとは無理に挑まなくてもOK + 
・三鬼神、四聖獣奇譚、ウェルリト戦役
| 極蛮神系クエスト | ★☆☆ | 戦闘系の微高難易度コンテンツ、武器やマウントが欲しいとかが無ければ特に…
| レイド（ノーマル）系クエスト | ★★☆ | 8人レイド、ストーリーが良い、装備集めもできる、ただ、戦闘が苦手なひとは無理に挑まなくてもOK + 
・アレキサンダー、オメガ、エデン、パンデモニウム
| レイド（零式）系クエスト | ★☆☆ | 戦闘系の高難易度コンテンツ、戦闘好き・マウント欲しい・最強装備を集めたいとかでなければ不要（FF14のアクティブユーザの3割くらいが挑むんだったか…） + 
アレキサンダー零式、オメガ零式、エデン零式、パンデモニウム零式
| アライアンスレイド系クエスト | ★★☆ | 24人レイド、ストーリーが良い、装備集めもできる、ただ、戦闘が苦手なひとは無理に挑まなくてもOK + 
・シャドウ・オブ・マハ、リターン・トゥ・イヴァリース、YoRHA:Dark Apocalypse、ミソロジーオブエオルゼア
| PVPコンテンツ | ★☆☆ | PVPが好き、マウント・装備が欲しいならおすすめ、ストーリー上は不要・特にストーリーもない？（やってないから不明）
| ゴールドソーサクエスト | ★☆☆ | 対象のゲームがしたい（麻雀・チョコボレース・イベント）したいとか、MIP交換マウントが欲しいとかでなければそんなに…
| 風脈開放クエスト | ★★☆ | 空が飛べないので風脈は開放しておきたい、歩くぜ！って人は不要
| ヒルディクエスト | ★☆☆ | ストーリーが面白い、このシリーズが好きな人は多いのでやっとくと良い
| DD系クエスト | ★☆☆ | DD（ディープダンジョン）系クエスト、4人以下のパーティで挑むフレキシブルダンジョン攻略、DDでしか使えない武器や装備を育てて光る武器を持ち出すことができるので、その辺に興味があれば… + 
・死者の迷宮、アメノミハシラ、オルト・エウレカ
| ウェポンクエスト | ★☆☆ | 拡張の合間に最強武器を少しづつ自分好みにカスタマイズしながら作成するコンテンツ、ストーリーもある、そこそこ時間泥棒なので無理せず + 
・ゾディアックウェポン（ZW）、アニマウェポン（AW）、エウレカウェポン（EW）、レジスタンスウェポン（RW）
| シーズナルイベント + 
（季節系イベント） | ★★★ | 星芒祭（クリスマス）、エッグハント（イースター）などをもとにしたエオルゼア内での季節性イベント、期間があるのでその間に実施する、マウントやおしゃれ装備などが貰えることが多いのでおすすめ
| サブクエスト | ☆☆☆ | 世界観・ストーリー好きじゃなければ特に…中には連続系の面白いのもある

| ハウジング | ★☆☆ | 家を持つのは推奨（ログオフ場所の確保的に）、外観や内装づくりに嵌る人は超嵌る、ハウジングはFF14の究極のエンドコンテンツらしいのです…

|===

==== 戦闘系ロールで忘れがちな動きの補足
[horizontal]
タンク:: 敵の詠唱を止めよう！ + 
敵の詠唱バーが赤く光って点滅してたら、ロールアクション「インジェクター」で止められる
ヒーラー:: メンバーに付与されたデバフを解除しよう！ + 
白い線付きのデバフは状態異常回復系のアクション（エスナなど）で解除できるので、積極的に解除する + 
（詳細は https://game8.jp/ff14/295909[バフ/デバフの意味とエスナで解除できるデバフの見分け方] 参照）
DPS:: 支援技（与ダメアップ系、回復系、被ダメ軽減系）も使おう！

==== FAQ
[qanda]
頭装備つけて話しかけろって言われたけどどうしたら？::
「よろず屋」や「防具屋」で頭装備を購入して、マイキャラクターの頭装備欄を選択して購入した装備をセットしてから、話しかければOK

頭装備購入したのに装備できないが…なぜ？::
装備にはジョブやクラス専用、男/女それぞれ専用など、特定の条件でないと装備出来ない物がある + 
装備の「ITEM LEVEL（アイテムレベル）」の下にどのようなジョブやクラス用かと、装備できるレベル条件が示されている + 
その欄が緑色であれば現在のジョブやレベルで装備できるが、その欄が赤色だと装備できない + 
また、白色は装備できるが適切な装備ではないので緑文字の装備を装備しよう

（序盤）ギルはどうためる？::
・サブクエストをいくつかこなすと報酬としてもらえる + 
・微々たるものだが、敵がドロップしたアイテムもよろず屋などで1Gとかで売れる + 
・コンテンツファインダーの申請の攻略報酬としてもらえる + 
…その辺を駆使して稼いでください

装備の見た目がダサすぎるのだが、どうにかできないか…？::
ミラプリで自分が持っている別の装備の見た目に変更できます + 
（詳細： https://game8.jp/ff14/301040[【FF14】ミラプリ解放条件｜やり方] 参照）

敵のドロップアイテム（革とか何とかの液体とか）っている？::
基本いらない、全売りでOK（よろず屋ととかに売却でOK）

IDの戦利品の「NEED、GREED、PASS」って何？どうしたらいいの？::
パーティでダンジョンに挑んだ場合に誰がドロップした戦利品を貰うかを決めるために行う（ロット）操作で、欲しい度合いを宣言するために選択する項目
* ロットルール：
** NEED（ぜひ欲しい）＜ GREED（欲しい）＜PASS（不要）
** 複数名が同じ項目を選択していた場合は、ロット選択時に表示された数値（ランダム）の大きいほうが勝ち
*** 補足：
**** NEEDは現在の職と装備の適性があっていないとロット出来ない
**** 全員がPASSした装備は捨てられる
**** 全員がロットする前ならNEED・GREEDからPASSには変更できるが、逆はできない
ロット勝負に文句をいう人はいないので、自分の好きな項目にロットをすればよい + 
装備の背景が緑や青のレア以上の装備は、グランドカンパニーで納品して軍票に変えられるので、所持品枠がないとかでなければNEED・GREEDでOK

マウント（乗り物）はいつ乗れるようになるの？::
マイチョコボを取得することで乗れる + 
（詳細： https://www.finalfantasyxiv.com/beginner/column/page11.html[チョコボはいつから乗れるの？] 参照）


空はいつ飛べるようになるの？::
新星エリアはLv50の究極幻想アルテマウェポンをクリア後に飛べる + 
蒼天移行のエリアは、対象エリアの風脈の泉をすべて開放することで飛べるようになる + 
（詳細： https://ff14wiki.info/?%E3%82%B3%E3%83%A9%E3%83%A0/%E3%83%95%E3%83%A9%E3%82%A4%E3%83%B3%E3%82%B0%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E3%81%AE%E5%8F%96%E5%BE%97%E6%96%B9%E6%B3%95[フライングマウントの取得方法
] 参照）

レベル50のダンジョンなのに、レベル50で申請できないのはなぜ？::
おそらくアイテムレベル制限を満たしていない + 
コンテンツファインダーで選択した対象のコンテンツ説明の「参加条件」に「平均アイテムレベル」が指定されいているが、参加申請した際に装備しているアイテムの平均値（アクセサリー含む）が参加条件を満たせていないものと思われる + 
ITEM LEVELの高い装備に変更して、平均アイテムレベルを満たして参加申請しよう + 
（詳細： https://choice-antenna.com/ff14-howtoitemlevel/[FF14 「アイテムレベル」とは？見方と上げ方の話^] ）

詩学って何？捨てていいの？::
トークンの一種で、一定量集めると強い装備と交換できるので、貯めて装備と交換が良い + 
詩学以外にも、最新パッチ用のトークンやレイド/極蛮神/零式レイドなど用のトークンがあるので不要じゃなければそれも捨てないようにご注意（古いノーマルレイドトークンはまぁ捨てても） + 
（詳細： https://game8.jp/ff14/455613[【FF14】詩学の効率的な集め方｜使い道^] 参照）


=== 用語集

[horizontal]
ID:: インスタンス・ダンジョンの略（4人パーティーで挑むダンジョンのこと）
PT:: パーティの略
CF:: コンテンツファインの略
LS:: リンクシェルの略（リンクシェル：加入したメンバーだけで会話ができる専用チャットチャンネル）
CWLS:: クロスワールドリンクシェルの略（論理データセンタ内で会話できるリンクシェル）
IL:: アイテムレベルの略
PVP:: プレイヤー対プレイヤー（英: Player versus player）の略、人対人で行なう対戦コンテンツのこと
RC:: レディチェックの略（レディチェック機能：パーティメンバーに対する「はい、いいえ」の投票機能）
ミラプリ:: ミラージュプリズムを利用した装備の見た目変更を行った格好や装備のことを示す（…と思う）
AF装備:: 拡張のMAXレベルの最初に貰えるジョブ専用装備のこと（アーティファクト装備の略？）
シャキる:: コンテンツファインダーのマッチングができて、対象コンテンツに突入できるようになること + 
（理由：コントローラーからこのタイミングで「シャキーン」という音がなるため）

先行入力:: リキャストタイムの後半に次のアクションを入力しておいて即時アクション実行を成功させる方法 + 
（詳細： https://gemajolife.net/ff14/ff14syosinnsya/3908[【FF14】WS・魔法・アビリティ・GCD・先行入力について|スキルUPに役立つ基本のお話^] ）

誤爆（ごばく）:: 自分が発言したかったチャットやLSと異なるチャットやLSに発言したこと + 
（「ごばく…」だけで、「誤爆して、すみません、無視してください」的な意味になる）

吉P:: FF14を立て直したプロデューサ兼ディレクターの吉田直樹さんのこと
