name: Asciidoc Build&Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.11
      uses: actions/setup-java@v3
      with:
        #distribution: 'adopt'
        java-version: '17'
        #cache: 'gradle
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew docs
    - name: Deploy
      # PR時にはDeployさせたくないので、merge時のみに実施する。
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
